name: forra
on:
  push:
  schedule:
    - cron: '2 */8 * * *'  # every 8 hours at minute 2

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: chsy
        run: python albatross-python/albatross/plugin.py

